name: Deploy no Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/meu-app:latest .

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKER_USERNAME }}/meu-app:latest

      - name: Atualizar serviço no Swarm via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/meu-app:latest webstack_web
